### PR TITLE
Document VKEY_MAX_ENTITY_COUNT

### PR DESCRIPTION
**Pull request by jeffreylovitz**

### CODE REVIEW

**Comment by swilly22** [comment]
As I see it, users aren't supposed to mess with this configuration, it is too "internal" if possible I would prefer to keep it undocumented

**Comment by jeffreylovitz** [comment]
> As I see it, users aren't supposed to mess with this configuration, it is too "internal" if possible I would prefer to keep it undocumented

@LiorKogan What's your take?

FWIW the other undocumented configuration are `ASYNC_DELETE` and `DELTA_MAX_PENDING_CHANGES`.

**Comment by LiorKogan** [comment]
I'm not sure.
On one side, undocumented configuration parameters are a bad thing. It is somewhat unprofessional, and it can cause even more damage.
On the other side, we don't want 'smart' people to play with them.

Maybe what we should do, is add a list of the parameter names in the documentation, without explaining them, and add something like "To ensure stability, the values of the following internal configuration parameters should not be modified unless instructed otherwise: ..."

**Comment by jeffreylovitz** [comment]
My own take matches Lior's recommendation - we should document all 3 of these configurations under a subheading like `Debug configurations`, and preface that section with a warning that these should only be modified if directed to do so.

Since they are exposed to the user by `CONFIG GET *`, they are already not hidden from a user's perspective.

**Pull request merged**
